### ISSUE TITLE
ExpoGo & Expo dev client error

### ISSUE THREAD

**Issue by serkansepil** [frw/react-native-ssl-public-key-pinning#69]
`Error: The package 'react-native-ssl-public-key-pinning' doesn't seem to be linked. Make sure:

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo Go`

Hi, i am using expo go & expo dev-client, getting error like this.

"react-native": "0.71.8"
Expo 48

**Comment by frw** [comment]
As mentioned in the error message, you cannot use Expo Go when using this library.

You will need to create a development build to test out the pinning as Expo Go won't have this library included. You can do this by building a development build locally (https://docs.expo.dev/develop/development-builds/development-workflows/#build-locally-with-android-studio-and-xcode), or you can use Expo EAS to create a development build (https://docs.expo.dev/develop/development-builds/create-a-build/).

You can still use Expo Go for development if you'd like, but you'll need to make sure that the SSL pinning library is available using `isSslPinningAvailable` before calling `initializeSslPinning`(https://github.com/frw/react-native-ssl-public-key-pinning#api-reference). Otherwise there'll be an exception, as you have found above, when calling `initializeSslPinning` in Expo Go.

**Comment by serkansepil** [comment]
Thanks for reply;

it is working good when i run with **npx expo run:ios** or in dev-client with eas development. Thanks for reply
